# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Metni')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Haberler',
                'verbose_name': 'Haber',
                'ordering': ('-created',),
            },
        ),
    ]
