# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Metni'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Metni'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Metni'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
    ]
