# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.News'),
        ),
    ]
