# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160918_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu_adı')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site_urli')),
            ],
        ),
    ]
