# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu_adı'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu_adı'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu_adı'),
        ),
    ]
