# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Şekil')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
