# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160929_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='adı')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='alıntı')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Takim',
                'verbose_name_plural': 'Takimlar',
            },
        ),
    ]
