# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
