# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_teams_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='alıntı'),
        ),
    ]
