# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20160929_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='adresi')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='numara')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name_plural': 'kontaklar',
                'ordering': ('-id',),
                'verbose_name': 'İletişim',
            },
        ),
    ]
