# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20161006_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Adi')),
                ('text_tr', models.CharField(max_length=255, null=True, verbose_name='Adi')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='Adi')),
                ('text_ru', models.CharField(max_length=255, null=True, verbose_name='Adi')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
                'ordering': ('-id',),
                'verbose_name': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collection/', verbose_name='Şekli')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
            options={
                'verbose_name_plural': 'Koleksiyonlar',
                'ordering': ('-id',),
                'verbose_name': 'Koleksiyon',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reference/', verbose_name='Şekli')),
            ],
            options={
                'verbose_name_plural': 'Referanslarimiz',
                'ordering': ('-id',),
                'verbose_name': 'Referans',
            },
        ),
    ]
