# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_category_collection_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Tipi'),
        ),
    ]
